import { Router, type IRouter } from "express";
import healthRouter from "./health";
import workspaceRouter from "./workspace";
import identityRouter from "./identity";
import businessTwinRouter from "./business-twin";
import icpRouter from "./icp";
import companiesRouter from "./companies";
import dataImportRouter from "./data-import";
import evidenceRouter from "./evidence";
import factsRouter from "./facts";
import researchRouter from "./research";
import signalsRouter from "./signals";
import opportunityPacksRouter from "./opportunity-packs";
import signalClustersRouter from "./signal-clusters";
import opportunityEngineRouter from "./opportunity-engine";
import peopleRouter from "./people";
import recommendationLedgerRouter from "./recommendation-ledger";
import learningRouter from "./learning";
import discoveryRouter from "./discovery";
import adminQualityRouter from "./admin-quality";
import intelligenceV2Router from "./intelligence-v2";
import marketReadinessRouter from "./market-readiness";

const router: IRouter = Router();

router.use(healthRouter);
router.use(workspaceRouter);
router.use(identityRouter);
router.use(businessTwinRouter);
router.use(icpRouter);
router.use(companiesRouter);
router.use(dataImportRouter);
router.use(evidenceRouter);
router.use(factsRouter);
router.use(researchRouter);
router.use(signalsRouter);
router.use(opportunityPacksRouter);
router.use(signalClustersRouter);
router.use(opportunityEngineRouter);
router.use(peopleRouter);
router.use(recommendationLedgerRouter);
router.use(learningRouter);
router.use(discoveryRouter);
router.use(adminQualityRouter);
router.use(intelligenceV2Router);
router.use(marketReadinessRouter);

export default router;
